# Generated by Django 5.2.4 on 2025-08-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopkart', '0005_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='producut',
            new_name='product',
        ),
    ]
